export const quotes = {
  motivational_and_tree_facts: {
    motivational_tips: [
      "Focus on consistency, not perfection. Small steps every day lead to lasting change.",
      "Start with one habit at a time. Trying to change everything at once can be overwhelming.",
      "Track your progress. Use a journal or app to monitor your habits and identify patterns.",
      "Prioritize sleep. A rested mind and body are essential for productivity and good health.",
      "Drink water first thing in the morning. Hydrate to kickstart your metabolism and boost energy.",
      "Plan your meals ahead of time. Reduces the temptation to make unhealthy last-minute decisions.",
      "Make exercise a part of your routine, not a task. Schedule it like any other important activity.",
      "Don't rely on willpower alone. Build an environment that supports your goals, like keeping healthy snacks accessible.",
      "Limit distractions during work or study time. Use tools like the Pomodoro technique to stay focused.",
      "Set realistic goals. Break big tasks into smaller, manageable steps.",
      "Celebrate small victories. Acknowledge your progress to stay motivated.",
      "Practice mindfulness. It helps reduce stress and improve focus on the task at hand.",
      "Prioritize mental health. Take breaks, meditate, or do something that recharges you.",
      "Make time for relaxation. Don’t overwork yourself; balance is key to long-term success.",
      "Adopt a growth mindset. Embrace mistakes as opportunities to learn and improve.",
      "Keep a morning routine. Start your day with a habit that sets a positive tone, like stretching or reading.",
      "Stay organized. Decluttering your space helps clear your mind and reduces stress.",
      "Use the two-minute rule. If a task takes less than two minutes, do it immediately.",
      "Set boundaries. Protect your time and energy by learning to say no when necessary.",
      "Eat mindfully. Pay attention to what and how much you're eating to avoid overeating.",
      "Practice gratitude. A daily gratitude habit can improve mental health and well-being.",
      "Take breaks during long tasks. Short pauses help maintain focus and productivity.",
      "Do things that align with your values. The more meaningful a habit, the easier it will be to sustain.",
      "Automate where possible. Set up systems to minimize effort on repetitive tasks (e.g., auto-savings, meal planning).",
      "Reflect regularly on your progress. Adjust goals if necessary and celebrate your efforts.",
      "Avoid multitasking. Focus on one task at a time to do it more effectively.",
      "Start with the most important task. Tackle the hardest or most essential task first, when your energy is highest.",
      "Create a designated space for work or exercise. It helps signal to your brain that it's time to focus.",
      "Be patient with yourself. Sustainable change takes time; don’t rush the process.",
      "Develop a support network. Surround yourself with people who encourage your growth.",
      "Practice time blocking. Allocate specific blocks of time for each task to ensure efficiency.",
      "Reduce screen time before bed. It improves sleep quality and helps you wake up feeling more refreshed.",
      "Do a quick workout during breaks. Even a few minutes of movement can boost energy and mood.",
      "Create habits, not goals. Systems of behavior are more effective than focusing only on outcomes.",
      "Practice self-compassion. Be kind to yourself when you slip up; it's part of the process.",
      "Break tasks into smaller, manageable parts. This reduces overwhelm and makes them seem less daunting.",
      "Commit to long-term health, not quick fixes. Healthy habits build over time and yield lasting results.",
      "Limit decision fatigue. Simplify daily choices (e.g., meal prep, setting out workout clothes the night before).",
      "Learn to embrace discomfort. Growth often happens when you're outside your comfort zone.",
      "Visualize success. Picture yourself achieving your goals to reinforce positive behaviors.",
      "Focus on what you can control. Acknowledge the factors within your power and let go of others.",
      "Don’t compare your progress to others. Everyone’s journey is different.",
      "Spend time outdoors. Nature has been shown to reduce stress and increase happiness.",
      "Stay flexible. Life can be unpredictable; adjust your habits when necessary without feeling discouraged.",
      "Make sustainable choices. Small, eco-friendly changes in your daily routine can add up over time.",
      "Use positive reinforcement. Reward yourself for sticking to healthy habits.",
      "Don’t wait for motivation. Take action even when you don’t feel like it—momentum builds over time.",
      "Be mindful of your energy levels. Adjust tasks based on how you feel; work when you're energized, rest when you're not.",
      "Set intentions for the day. A clear purpose helps you stay on track and focused.",
      "Remember, progress is not linear. Embrace setbacks as learning experiences rather than failures.",
    ],
    tree_facts: [
      "Trees are the longest-living organisms on Earth. Some trees, like the Bristlecone Pine, can live for over 5,000 years.",
      "A single mature tree can absorb carbon dioxide at a rate of 48 pounds per year.",
      "Trees release oxygen. A single tree can produce enough oxygen for up to four people to breathe.",
      "The tallest tree in the world is a coast redwood named Hyperion, standing at 379.7 feet tall.",
      "Tree roots can communicate. Trees in a forest communicate with each other via underground fungal networks, sometimes called the 'Wood Wide Web.'",
      "Trees can 'hear.' Research shows that trees may be able to sense vibrations in their environment.",
      "The world's heaviest tree is a giant sequoia called General Sherman, weighing about 2.7 million pounds.",
      "The oldest tree in the world is a clonal colony of Quaking Aspen in Utah, estimated to be around 80,000 years old.",
      "Some trees have thorns to protect themselves from herbivores, like the Acacia tree.",
      "Trees can 'breathe' through tiny pores on their leaves called stomata.",
      "The Amazon rainforest is often called the 'lungs of the Earth' because it produces 20% of the world's oxygen.",
      "Not all trees have leaves. Some, like conifers, have needles instead.",
      "Trees can help reduce noise pollution by acting as natural sound barriers.",
      "A tree’s canopy can reduce the effects of global warming. Trees cool the air by releasing water vapor.",
      "Trees have been used as landmarks for centuries, with some trees acting as navigational guides for travelers.",
      "The Baobab tree is known as the 'tree of life' because it stores water in its trunk, allowing it to survive in arid climates.",
      "Some trees can change color in the fall because they break down chlorophyll, revealing other pigments.",
      "There are over 3 trillion trees on Earth. That’s about 400 trees for every person on the planet!",
      "A tree’s bark is like its skin, providing protection from the elements, pests, and diseases.",
      "Trees have been shown to improve mental health, reducing stress and promoting relaxation.",
      "A tree can have thousands of leaves, all of which work together to collect sunlight for photosynthesis.",
      "The world's largest flower blooms on the Rafflesia arnoldii tree and has a strong odor resembling rotting flesh.",
      "Trees are great at filtering air, removing dust, pollutants, and toxins from the air around us.",
      "Trees can be used as natural medicine. For example, the bark of the willow tree contains salicin, the basis for aspirin.",
      "Coconut trees can grow up to 100 feet tall and are able to produce coconuts year-round.",
      "The Redwood National and State Parks in California are home to some of the world's oldest and tallest trees.",
      "Maple trees produce sap, which is used to make maple syrup.",
      "The longest-lived individual tree is a Bristlecone Pine in California, aged more than 5,000 years.",
      "Willow trees can grow in water, often found along rivers and streams.",
      "The largest fruit-bearing tree is the Breadfruit tree, whose fruit can grow up to 20 pounds.",
      "The 'Tsunami tree' of Japan survived the 2011 tsunami and became a symbol of resilience.",
      "The Uprooted tree phenomenon occurs when the roots of a tree are lifted from the soil due to natural disasters.",
      "An oak tree can produce up to 10,000 acorns in a single year!",
      "Trees produce natural oils, like eucalyptus and pine, that are used in aromatherapy and perfumes.",
      "Some trees can 'sleep' at night, closing their leaves or flowers to conserve energy.",
    ],
  },
};
